repos:
  - repo: local
    hooks:
      - id: ruff-lint
        name: Ruff Linter
        entry: pdm run ruff check --fix
        language: system
        types: [python]
        args: []

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
        exclude: ^migrations/
      - id: check-json
        exclude: ^migrations/
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-ast
        exclude: ^migrations/
      - id: debug-statements
        exclude: ^migrations/


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        exclude: ^(migrations/|tests/)
        additional_dependencies:
          - types-PyYAML
          - types-requests
        args: [--ignore-missing-imports, --no-strict-optional]
