target-version = "py313"
line-length = 130

[lint]
preview = true
select = ["F", "E", "W", "I", "B", "D", "RUF"]
ignore = [
    # Documentation pragmatism 
    "D100", "D101", "D102", "D103", "D104", "D107", "D209", "D212", "D415",
    # Code quality exceptions
    "B008",
    # Asymmetric alignment preservation
    "E203", "E221", "E241", "E251",
]

[lint.pydocstyle]
convention = "google"

[lint.isort]
force-single-line = false
combine-as-imports = true
no-sections = true
split-on-trailing-comma = true
force-sort-within-sections = true
no-lines-before = ["future", "standard-library", "third-party", "first-party", "local-folder"]
