name: Security Checks

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  schedule:
    - cron: "0 2 * * 0" # Weekly on Sunday at 2 AM

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pdm install --dev --no-self

      - name: Run Bandit security scan
        run: |
          pdm run bandit -r src/ -f json -o bandit-report.json || true
          pdm run bandit -r src/ --severity-level high

      - name: Run pip-audit for dependency vulnerabilities
        run: |
          echo "Running pip-audit to check for known vulnerabilities..."
          # Temporarily ignore GHSA-4xh5-x5gv-qwph (pip 25.2 tarfile issue) until pip 25.3 is released
          pdm run pip-audit --format=json --output=pip-audit-report.json --ignore-vuln GHSA-4xh5-x5gv-qwph || true
          echo "Summary of vulnerabilities:"
          pdm run pip-audit --desc --ignore-vuln GHSA-4xh5-x5gv-qwph

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-reports
          path: |
            bandit-report.json
            pip-audit-report.json
